version: '3.8'

services:
  nats:
    image: nats:latest
    ports:
      - "4222:4222"
      - "8222:8222"
    command: "--jetstream --http_port 8222"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8222/varz"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - tyndau-network

  notification-service:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      nats:
        condition: service_healthy
    environment:
      - NATS_URL=nats://nats:4222
      - NATS_STREAM=tyndau
      # Add these new environment variables for consumer configuration
      - NATS_CONSUMER_PREFIX=tyndau_consumer
      - NATS_SUBJECT_USER_REGISTERED=user_registered
      # SMTP configuration
      - SMTP_HOST=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_USERNAME=tamutdzhin@gmail.com
      - SMTP_PASSWORD=pktpusxmnalycizh 
      - SMTP_FROM=tamutdzhin@gmail.com
      - TEMPLATES_DIR=/app/templates
    networks:
      - tyndau-network

networks:
  tyndau-network:
    driver: bridge

