// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: Tyndau/music-service/internal/api/song/v1/song.proto

package songv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Song struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Artist        string                 `protobuf:"bytes,3,opt,name=artist,proto3" json:"artist,omitempty"`
	Album         string                 `protobuf:"bytes,4,opt,name=album,proto3" json:"album,omitempty"`
	Genre         string                 `protobuf:"bytes,5,opt,name=genre,proto3" json:"genre,omitempty"`
	DurationSec   int32                  `protobuf:"varint,6,opt,name=duration_sec,json=durationSec,proto3" json:"duration_sec,omitempty"`
	FileUrl       string                 `protobuf:"bytes,7,opt,name=file_url,json=fileUrl,proto3" json:"file_url,omitempty"`
	ReleasedAt    *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=released_at,json=releasedAt,proto3" json:"released_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Song) Reset() {
	*x = Song{}
	mi := &file_Tyndau_music_service_internal_api_song_v1_song_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Song) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Song) ProtoMessage() {}

func (x *Song) ProtoReflect() protoreflect.Message {
	mi := &file_Tyndau_music_service_internal_api_song_v1_song_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Song.ProtoReflect.Descriptor instead.
func (*Song) Descriptor() ([]byte, []int) {
	return file_Tyndau_music_service_internal_api_song_v1_song_proto_rawDescGZIP(), []int{0}
}

func (x *Song) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Song) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Song) GetArtist() string {
	if x != nil {
		return x.Artist
	}
	return ""
}

func (x *Song) GetAlbum() string {
	if x != nil {
		return x.Album
	}
	return ""
}

func (x *Song) GetGenre() string {
	if x != nil {
		return x.Genre
	}
	return ""
}

func (x *Song) GetDurationSec() int32 {
	if x != nil {
		return x.DurationSec
	}
	return 0
}

func (x *Song) GetFileUrl() string {
	if x != nil {
		return x.FileUrl
	}
	return ""
}

func (x *Song) GetReleasedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ReleasedAt
	}
	return nil
}

type CreateSongRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Song          *Song                  `protobuf:"bytes,1,opt,name=song,proto3" json:"song,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSongRequest) Reset() {
	*x = CreateSongRequest{}
	mi := &file_Tyndau_music_service_internal_api_song_v1_song_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSongRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSongRequest) ProtoMessage() {}

func (x *CreateSongRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Tyndau_music_service_internal_api_song_v1_song_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSongRequest.ProtoReflect.Descriptor instead.
func (*CreateSongRequest) Descriptor() ([]byte, []int) {
	return file_Tyndau_music_service_internal_api_song_v1_song_proto_rawDescGZIP(), []int{1}
}

func (x *CreateSongRequest) GetSong() *Song {
	if x != nil {
		return x.Song
	}
	return nil
}

type GetSongRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSongRequest) Reset() {
	*x = GetSongRequest{}
	mi := &file_Tyndau_music_service_internal_api_song_v1_song_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSongRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSongRequest) ProtoMessage() {}

func (x *GetSongRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Tyndau_music_service_internal_api_song_v1_song_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSongRequest.ProtoReflect.Descriptor instead.
func (*GetSongRequest) Descriptor() ([]byte, []int) {
	return file_Tyndau_music_service_internal_api_song_v1_song_proto_rawDescGZIP(), []int{2}
}

func (x *GetSongRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ListSongsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSongsRequest) Reset() {
	*x = ListSongsRequest{}
	mi := &file_Tyndau_music_service_internal_api_song_v1_song_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSongsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSongsRequest) ProtoMessage() {}

func (x *ListSongsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Tyndau_music_service_internal_api_song_v1_song_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSongsRequest.ProtoReflect.Descriptor instead.
func (*ListSongsRequest) Descriptor() ([]byte, []int) {
	return file_Tyndau_music_service_internal_api_song_v1_song_proto_rawDescGZIP(), []int{3}
}

func (x *ListSongsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListSongsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListSongsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Songs         []*Song                `protobuf:"bytes,1,rep,name=songs,proto3" json:"songs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSongsResponse) Reset() {
	*x = ListSongsResponse{}
	mi := &file_Tyndau_music_service_internal_api_song_v1_song_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSongsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSongsResponse) ProtoMessage() {}

func (x *ListSongsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_Tyndau_music_service_internal_api_song_v1_song_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSongsResponse.ProtoReflect.Descriptor instead.
func (*ListSongsResponse) Descriptor() ([]byte, []int) {
	return file_Tyndau_music_service_internal_api_song_v1_song_proto_rawDescGZIP(), []int{4}
}

func (x *ListSongsResponse) GetSongs() []*Song {
	if x != nil {
		return x.Songs
	}
	return nil
}

type UpdateSongRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Song          *Song                  `protobuf:"bytes,1,opt,name=song,proto3" json:"song,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSongRequest) Reset() {
	*x = UpdateSongRequest{}
	mi := &file_Tyndau_music_service_internal_api_song_v1_song_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSongRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSongRequest) ProtoMessage() {}

func (x *UpdateSongRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Tyndau_music_service_internal_api_song_v1_song_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSongRequest.ProtoReflect.Descriptor instead.
func (*UpdateSongRequest) Descriptor() ([]byte, []int) {
	return file_Tyndau_music_service_internal_api_song_v1_song_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateSongRequest) GetSong() *Song {
	if x != nil {
		return x.Song
	}
	return nil
}

type DeleteSongRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSongRequest) Reset() {
	*x = DeleteSongRequest{}
	mi := &file_Tyndau_music_service_internal_api_song_v1_song_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSongRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSongRequest) ProtoMessage() {}

func (x *DeleteSongRequest) ProtoReflect() protoreflect.Message {
	mi := &file_Tyndau_music_service_internal_api_song_v1_song_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSongRequest.ProtoReflect.Descriptor instead.
func (*DeleteSongRequest) Descriptor() ([]byte, []int) {
	return file_Tyndau_music_service_internal_api_song_v1_song_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteSongRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

var File_Tyndau_music_service_internal_api_song_v1_song_proto protoreflect.FileDescriptor

const file_Tyndau_music_service_internal_api_song_v1_song_proto_rawDesc = "" +
	"\n" +
	"4Tyndau/music-service/internal/api/song/v1/song.proto\x12\asong.v1\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xeb\x01\n" +
	"\x04Song\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x16\n" +
	"\x06artist\x18\x03 \x01(\tR\x06artist\x12\x14\n" +
	"\x05album\x18\x04 \x01(\tR\x05album\x12\x14\n" +
	"\x05genre\x18\x05 \x01(\tR\x05genre\x12!\n" +
	"\fduration_sec\x18\x06 \x01(\x05R\vdurationSec\x12\x19\n" +
	"\bfile_url\x18\a \x01(\tR\afileUrl\x12;\n" +
	"\vreleased_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"releasedAt\"6\n" +
	"\x11CreateSongRequest\x12!\n" +
	"\x04song\x18\x01 \x01(\v2\r.song.v1.SongR\x04song\" \n" +
	"\x0eGetSongRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"@\n" +
	"\x10ListSongsRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\"8\n" +
	"\x11ListSongsResponse\x12#\n" +
	"\x05songs\x18\x01 \x03(\v2\r.song.v1.SongR\x05songs\"6\n" +
	"\x11UpdateSongRequest\x12!\n" +
	"\x04song\x18\x01 \x01(\v2\r.song.v1.SongR\x04song\"#\n" +
	"\x11DeleteSongRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id2\xc1\x02\n" +
	"\vSongService\x127\n" +
	"\n" +
	"CreateSong\x12\x1a.song.v1.CreateSongRequest\x1a\r.song.v1.Song\x121\n" +
	"\aGetSong\x12\x17.song.v1.GetSongRequest\x1a\r.song.v1.Song\x12B\n" +
	"\tListSongs\x12\x19.song.v1.ListSongsRequest\x1a\x1a.song.v1.ListSongsResponse\x12@\n" +
	"\n" +
	"UpdateSong\x12\x1a.song.v1.UpdateSongRequest\x1a\x16.google.protobuf.Empty\x12@\n" +
	"\n" +
	"DeleteSong\x12\x1a.song.v1.DeleteSongRequest\x1a\x16.google.protobuf.EmptyB?Z=github.com/Temutjin2k/Tyndau/music-service/api/song/v1;songv1b\x06proto3"

var (
	file_Tyndau_music_service_internal_api_song_v1_song_proto_rawDescOnce sync.Once
	file_Tyndau_music_service_internal_api_song_v1_song_proto_rawDescData []byte
)

func file_Tyndau_music_service_internal_api_song_v1_song_proto_rawDescGZIP() []byte {
	file_Tyndau_music_service_internal_api_song_v1_song_proto_rawDescOnce.Do(func() {
		file_Tyndau_music_service_internal_api_song_v1_song_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_Tyndau_music_service_internal_api_song_v1_song_proto_rawDesc), len(file_Tyndau_music_service_internal_api_song_v1_song_proto_rawDesc)))
	})
	return file_Tyndau_music_service_internal_api_song_v1_song_proto_rawDescData
}

var file_Tyndau_music_service_internal_api_song_v1_song_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_Tyndau_music_service_internal_api_song_v1_song_proto_goTypes = []any{
	(*Song)(nil),                  // 0: song.v1.Song
	(*CreateSongRequest)(nil),     // 1: song.v1.CreateSongRequest
	(*GetSongRequest)(nil),        // 2: song.v1.GetSongRequest
	(*ListSongsRequest)(nil),      // 3: song.v1.ListSongsRequest
	(*ListSongsResponse)(nil),     // 4: song.v1.ListSongsResponse
	(*UpdateSongRequest)(nil),     // 5: song.v1.UpdateSongRequest
	(*DeleteSongRequest)(nil),     // 6: song.v1.DeleteSongRequest
	(*timestamppb.Timestamp)(nil), // 7: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),         // 8: google.protobuf.Empty
}
var file_Tyndau_music_service_internal_api_song_v1_song_proto_depIdxs = []int32{
	7, // 0: song.v1.Song.released_at:type_name -> google.protobuf.Timestamp
	0, // 1: song.v1.CreateSongRequest.song:type_name -> song.v1.Song
	0, // 2: song.v1.ListSongsResponse.songs:type_name -> song.v1.Song
	0, // 3: song.v1.UpdateSongRequest.song:type_name -> song.v1.Song
	1, // 4: song.v1.SongService.CreateSong:input_type -> song.v1.CreateSongRequest
	2, // 5: song.v1.SongService.GetSong:input_type -> song.v1.GetSongRequest
	3, // 6: song.v1.SongService.ListSongs:input_type -> song.v1.ListSongsRequest
	5, // 7: song.v1.SongService.UpdateSong:input_type -> song.v1.UpdateSongRequest
	6, // 8: song.v1.SongService.DeleteSong:input_type -> song.v1.DeleteSongRequest
	0, // 9: song.v1.SongService.CreateSong:output_type -> song.v1.Song
	0, // 10: song.v1.SongService.GetSong:output_type -> song.v1.Song
	4, // 11: song.v1.SongService.ListSongs:output_type -> song.v1.ListSongsResponse
	8, // 12: song.v1.SongService.UpdateSong:output_type -> google.protobuf.Empty
	8, // 13: song.v1.SongService.DeleteSong:output_type -> google.protobuf.Empty
	9, // [9:14] is the sub-list for method output_type
	4, // [4:9] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_Tyndau_music_service_internal_api_song_v1_song_proto_init() }
func file_Tyndau_music_service_internal_api_song_v1_song_proto_init() {
	if File_Tyndau_music_service_internal_api_song_v1_song_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_Tyndau_music_service_internal_api_song_v1_song_proto_rawDesc), len(file_Tyndau_music_service_internal_api_song_v1_song_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_Tyndau_music_service_internal_api_song_v1_song_proto_goTypes,
		DependencyIndexes: file_Tyndau_music_service_internal_api_song_v1_song_proto_depIdxs,
		MessageInfos:      file_Tyndau_music_service_internal_api_song_v1_song_proto_msgTypes,
	}.Build()
	File_Tyndau_music_service_internal_api_song_v1_song_proto = out.File
	file_Tyndau_music_service_internal_api_song_v1_song_proto_goTypes = nil
	file_Tyndau_music_service_internal_api_song_v1_song_proto_depIdxs = nil
}
